apiVersion: v1
kind: Pod
metadata:
  name: hello-go
  labels:
    app: hello-go
spec:
  containers:
    - name: goserver
      image: edsonluiz/hello-go:1.0
      imagePullPolicy: Always
      ports:
        - containerPort: 80