apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-go
  labels:
    app: hello-go
    key: value
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      name: hello-go
      labels:
        app: hello-go
    spec:
      containers:
        - name: hello-go
          image: edsonluiz/hello-go:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
